import parser from "@typescript-eslint/parser";
import plugin from "@typescript-eslint/eslint-plugin";

export default [
  {
    ignores: ["**/dist/", "**/target/"],
  },
  {
    files: ["**/*.js", "**/*.ts"],
    plugins: { "@typescript-eslint": plugin },
    languageOptions: {
      parser,
      parserOptions: { projectService: true },
    },
    rules: {
      // See https://typescript-eslint.io/rules/
      "@typescript-eslint/adjacent-overload-signatures": 2,
      "@typescript-eslint/array-type": 2,
      "@typescript-eslint/await-thenable": 2,
      "@typescript-eslint/ban-ts-comment": 2,
      "@typescript-eslint/ban-tslint-comment": 2,
      "@typescript-eslint/class-literal-property-style": 2,
      "@typescript-eslint/class-methods-use-this": 0,
      "@typescript-eslint/consistent-generic-constructors": 2,
      "@typescript-eslint/consistent-indexed-object-style": 2,
      "@typescript-eslint/consistent-return": 2,
      "@typescript-eslint/consistent-type-assertions": 2,
      "@typescript-eslint/consistent-type-definitions": [2, "type"],
      "@typescript-eslint/consistent-type-exports": 2,
      "@typescript-eslint/consistent-type-imports": 2,
      "@typescript-eslint/default-param-last": 2,
      "@typescript-eslint/dot-notation": 2,
      "@typescript-eslint/explicit-function-return-type": 2,
      "@typescript-eslint/explicit-member-accessibility": [
        2,
        { accessibility: "no-public" },
      ],
      "@typescript-eslint/explicit-module-boundary-types": 2,
      "@typescript-eslint/init-declarations": 2,
      "@typescript-eslint/max-params": [2, { max: 5 }],
      "@typescript-eslint/member-ordering": 0,
      "@typescript-eslint/method-signature-style": 2,
      "@typescript-eslint/naming-convention": 0,
      "@typescript-eslint/no-array-constructor": 2,
      "@typescript-eslint/no-array-delete": 2,
      "@typescript-eslint/no-base-to-string": 2,
      "@typescript-eslint/no-confusing-non-null-assertion": 0,
      "@typescript-eslint/no-confusing-void-expression": 2,
      "@typescript-eslint/no-deprecated": 2,
      "@typescript-eslint/no-dupe-class-members": 2,
      "@typescript-eslint/no-duplicate-enum-values": 2,
      "@typescript-eslint/no-duplicate-type-constituents": 2,
      "@typescript-eslint/no-dynamic-delete": 2,
      "@typescript-eslint/no-empty-function": 2,
      "@typescript-eslint/no-empty-object-type": 2,
      "@typescript-eslint/no-explicit-any": 2,
      "@typescript-eslint/no-extra-non-null-assertion": 2,
      "@typescript-eslint/no-extraneous-class": 2,
      "@typescript-eslint/no-floating-promises": 2,
      "@typescript-eslint/no-for-in-array": 2,
      "@typescript-eslint/no-implied-eval": 2,
      "@typescript-eslint/no-import-type-side-effects": 2,
      "@typescript-eslint/no-inferrable-types": 2,
      "@typescript-eslint/no-invalid-this": 2,
      "@typescript-eslint/no-invalid-void-type": 2,
      "@typescript-eslint/no-loop-func": 2,
      "@typescript-eslint/no-magic-numbers": 0,
      "@typescript-eslint/no-meaningless-void-operator": 2,
      "@typescript-eslint/no-misused-new": 2,
      "@typescript-eslint/no-misused-promises": 2,
      "@typescript-eslint/no-misused-spread": 2,
      "@typescript-eslint/no-mixed-enums": 2,
      "@typescript-eslint/no-namespace": 2,
      "@typescript-eslint/no-non-null-asserted-nullish-coalescing": 2,
      "@typescript-eslint/no-non-null-asserted-optional-chain": 2,
      "@typescript-eslint/no-non-null-assertion": 0,
      "@typescript-eslint/no-redeclare": 2,
      "@typescript-eslint/no-redundant-type-constituents": 2,
      "@typescript-eslint/no-require-imports": 2,
      "@typescript-eslint/no-restricted-imports": 0,
      "@typescript-eslint/no-restricted-types": 2,
      "@typescript-eslint/no-shadow": 2,
      "@typescript-eslint/no-this-alias": [2, { allowedNames: ["self"] }],
      "@typescript-eslint/no-unnecessary-boolean-literal-compare": 2,
      "@typescript-eslint/no-unnecessary-condition": 2,
      "@typescript-eslint/no-unnecessary-parameter-property-assignment": 2,
      "@typescript-eslint/no-unnecessary-qualifier": 2,
      "@typescript-eslint/no-unnecessary-template-expression": 2,
      "@typescript-eslint/no-unnecessary-type-arguments": 2,
      "@typescript-eslint/no-unnecessary-type-assertion": 2,
      "@typescript-eslint/no-unnecessary-type-constraint": 2,
      "@typescript-eslint/no-unnecessary-type-conversion": 2,
      "@typescript-eslint/no-unnecessary-type-parameters": 2,
      "@typescript-eslint/no-unsafe-argument": 2,
      "@typescript-eslint/no-unsafe-assignment": 2,
      "@typescript-eslint/no-unsafe-call": 2,
      "@typescript-eslint/no-unsafe-declaration-merging": 2,
      "@typescript-eslint/no-unsafe-enum-comparison": 2,
      "@typescript-eslint/no-unsafe-function-type": 2,
      "@typescript-eslint/no-unsafe-member-access": 2,
      "@typescript-eslint/no-unsafe-return": 2,
      "@typescript-eslint/no-unsafe-type-assertion": 2,
      "@typescript-eslint/no-unsafe-unary-minus": 2,
      "@typescript-eslint/no-unused-expressions": 2,
      "@typescript-eslint/no-unused-private-class-members": 2,
      "@typescript-eslint/no-unused-vars": 2,
      "@typescript-eslint/no-use-before-define": 2,
      "@typescript-eslint/no-useless-constructor": 2,
      "@typescript-eslint/no-useless-default-assignment": 2,
      "@typescript-eslint/no-useless-empty-export": 2,
      "@typescript-eslint/no-wrapper-object-types": 2,
      "@typescript-eslint/non-nullable-type-assertion-style": 2,
      "@typescript-eslint/only-throw-error": 2,
      "@typescript-eslint/parameter-properties": 2,
      "@typescript-eslint/prefer-as-const": 2,
      "@typescript-eslint/prefer-destructuring": 2,
      "@typescript-eslint/prefer-enum-initializers": 0,
      "@typescript-eslint/prefer-find": 2,
      "@typescript-eslint/prefer-for-of": 2,
      "@typescript-eslint/prefer-function-type": 2,
      "@typescript-eslint/prefer-includes": 2,
      "@typescript-eslint/prefer-literal-enum-member": 2,
      "@typescript-eslint/prefer-namespace-keyword": 2,
      "@typescript-eslint/prefer-nullish-coalescing": 2,
      "@typescript-eslint/prefer-optional-chain": 2,
      "@typescript-eslint/prefer-promise-reject-errors": 0,
      "@typescript-eslint/prefer-readonly": 2,
      "@typescript-eslint/prefer-readonly-parameter-types": 2,
      "@typescript-eslint/prefer-reduce-type-parameter": 2,
      "@typescript-eslint/prefer-regexp-exec": 2,
      "@typescript-eslint/prefer-return-this-type": 2,
      "@typescript-eslint/prefer-string-starts-ends-with": [
        2,
        { allowSingleElementEquality: "always" },
      ],
      "@typescript-eslint/promise-function-async": 2,
      "@typescript-eslint/related-getter-setter-pairs": 2,
      "@typescript-eslint/require-array-sort-compare": 2,
      "@typescript-eslint/require-await": 2,
      "@typescript-eslint/restrict-plus-operands": [
        2,
        {
          allowAny: false,
          allowBoolean: false,
          allowNullish: false,
          allowNumberAndString: false,
          allowRegExp: false,
        },
      ],
      "@typescript-eslint/restrict-template-expressions": 0,
      "@typescript-eslint/return-await": [2, "always"],
      "@typescript-eslint/strict-boolean-expressions": 0,
      "@typescript-eslint/strict-void-return": 2,
      "@typescript-eslint/switch-exhaustiveness-check": 0,
      "@typescript-eslint/triple-slash-reference": [2, { types: "never" }],
      "@typescript-eslint/unbound-method": 2,
      "@typescript-eslint/unified-signatures": 2,
      "@typescript-eslint/use-unknown-in-catch-callback-variable": 2,
    },
  },
];
