name: ci

on:
  pull_request:
  push:
    branches: "*"

jobs:
  check:
    name: check
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          key: bun-${{ hashFiles('bun.lock') }}
          restore-keys: bun
          path: |
            node_modules
            ~/.bun/install/cache

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: Run linters
        run: bun run lint
